# Generated by Django 4.2.3 on 2023-07-20 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoneyAccount', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('inventory', models.DecimalField(decimal_places=2, default=100000.0, max_digits=10)),
                ('coefficient', models.DecimalField(decimal_places=2, default=0.5, max_digits=2)),
                ('deposit_interval', models.PositiveIntegerField(default=1)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='moneyaccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='moneyaccount',
            name='income',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=10),
        ),
    ]
