# Generated by Django 4.2.3 on 2023-07-30 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MoneyAccount', '0002_generalsource_alter_moneyaccount_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsource',
            name='deposit_interval',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('W', 'WITHDRAW'), ('D', 'DEPOSIT')], max_length=1)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_time', models.DateTimeField(auto_now_add=True)),
                ('general_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoneyAccount.generalsource')),
                ('money_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoneyAccount.moneyaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10)),
                ('coefficient_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('general_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoneyAccount.generalsource')),
                ('money_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoneyAccount.moneyaccount')),
            ],
        ),
    ]
