# Generated by Django 4.2.3 on 2023-08-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoneyAccount', '0003_alter_generalsource_deposit_interval_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='withdrawal_interval',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generalsource',
            name='deposit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
